// flow-typed signature: 00aebdeb6534dfb9821f8de392efdee2
// flow-typed version: <<STUB>>/karma-verbose-reporter_v0.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-verbose-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-verbose-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-verbose-reporter/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-verbose-reporter/reporter.js' {
  declare module.exports: $Exports<'karma-verbose-reporter/reporter'>;
}
