// flow-typed signature: aaa203a81cdaae69c864bd653996130f
// flow-typed version: <<STUB>>/proxy-middleware_v^0.15.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proxy-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'proxy-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'proxy-middleware/index' {
  declare module.exports: $Exports<'proxy-middleware'>;
}
declare module 'proxy-middleware/index.js' {
  declare module.exports: $Exports<'proxy-middleware'>;
}
