// flow-typed signature: f8405ada28f029fdd8e82d4eeb694735
// flow-typed version: <<STUB>>/vue-style-loader_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-style-loader/addStyles' {
  declare module.exports: any;
}

declare module 'vue-style-loader/addStyleUrl' {
  declare module.exports: any;
}

declare module 'vue-style-loader/url' {
  declare module.exports: any;
}

declare module 'vue-style-loader/useable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-style-loader/addStyles.js' {
  declare module.exports: $Exports<'vue-style-loader/addStyles'>;
}
declare module 'vue-style-loader/addStyleUrl.js' {
  declare module.exports: $Exports<'vue-style-loader/addStyleUrl'>;
}
declare module 'vue-style-loader/index' {
  declare module.exports: $Exports<'vue-style-loader'>;
}
declare module 'vue-style-loader/index.js' {
  declare module.exports: $Exports<'vue-style-loader'>;
}
declare module 'vue-style-loader/url.js' {
  declare module.exports: $Exports<'vue-style-loader/url'>;
}
declare module 'vue-style-loader/useable.js' {
  declare module.exports: $Exports<'vue-style-loader/useable'>;
}
