const TASK_STATUS = {
    PLAYING: 1,
    PAUSE: -1,
    PENDING: 0
};
const TASK_PRIORITY = {
    PRIORITY_0: 0,
    PRIORITY_1: 1,
    PRIORITY_2: 2
};
const DUEDATE_TYPE = {
    NORMAL: 'normal',
    WARNING: 'warning',
    DANGER: 'danger'
};
const MILLISECONDS_PER_HOUR = 60 * 60 * 1000;
const MILLISECONDS_PER_DAY = 24 * MILLISECONDS_PER_HOUR;
const MILLISECONDS_PER_WEEK = 7 * MILLISECONDS_PER_DAY;
const MILLISECONDS = {MILLISECONDS_PER_HOUR, MILLISECONDS_PER_DAY, MILLISECONDS_PER_WEEK};

export {
    TASK_STATUS,
    MILLISECONDS,
    TASK_PRIORITY,
    DUEDATE_TYPE
};
